<?php

namespace AppBundle\Repository;

/**
 * MedsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedsUserRepository extends \Doctrine\ORM\EntityRepository
{
}
