app:
    resource: '@AppBundle/Controller/Base'
    type: annotation
    prefix:   /v1/
    defaults: {_format:json}

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#admin_area:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin
#
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin
