# Learn more about Service, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for Service in *this* file
    _defaults:
        # automatically injects dependencies in your Service
        autowire: true
        # automatically registers your Service as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch Service directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual Service
        public: false

    # makes classes in src/AppBundle available to be used as Service
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint Service
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more Service, or override Service that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
